export const SIGN_IN_USERNAME_SUCCESS = 'SIGN_IN_USERNAME_SUCCESS';
export const SIGN_IN_USERNAME_FAILED = 'SIGN_IN_USERNAME_FAILED';
export const SIGN_IN_USERNAME_START = 'SIGN_IN_USERNAME_START';
export const SIGN_IN_USERNAME = 'SIGN_IN_USERNAME';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_USER_LOCAL_STORAGE_SUCCESS = 'GET_USER_LOCAL_STORAGE_SUCCESS';
export const GET_USER_LOCAL_STORAGE = 'GET_USER_LOCAL_STORAGE';

export const FILE_VALIDATION_ERROR = 'FILE_VALIDATION_ERROR';

export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';